### ISSUE TITLE
User Manual for WP Post Pillar Pages

### ISSUE THREAD

**Issue by inbndmrktggrp** [SimonMayerhofer/wp-post-pillar-pages#1]
### Yes I know, if I have to ask I shouldn't be trying to use the product!  :-)

None-the-less I installed it, actually understood the creation of new types, created posts within the new document-type but I'm having a problem figuring out how to present the documents collectively in some non-manual way.

If there is such a method, I'd really appreciate a referral to some resources that would help me figure it out.

If there isn't - **I volunteer to prepare suitable documentation** as my contribution to this initiative if you'll provide me content & direction!

Looking forward to your response,
Yoel Ben-Avraham
[Inbound Marketing Evangelist](https://www.inboundmarketing.group)

**Comment by SimonMayerhofer** [comment]
Hi Yoel, I'm happy to see this plugin is used by others. Feel free to ask any question. 
What do you mean by "how to present the documents collectively in some non-manual way". Have you an example for me to better understand what you're up to?

**Comment by inbndmrktggrp** [comment]
Simon Shalom,

Well, I have *no* problem creating  Custom Post Type. Also, none creating Pages or Posts within the new Menu option. 

Where I'm struggling is how to create a central TOC page that ties all the associated pages together (without having to do it manually). I'm currently experimenting with Organize Series that has some potential ... but I'm still thwarted by lack of examples as to how to create this illusive TOC page (not your plugin - not your problem),

Once I resolve this, I have every intention of sharing my "discovery" with as many people as possible. I've been an advocate for "an affordable Hubspot CMS" for over a decade and adding this feature, the ability to create true pilar pages will be a welcome addition to our arsenal!

Thank you in advance for any & all assistance extended!
If I can figure this out I "love" the simplicity and ease of use.  Most of the people I encourage to use Wordpress etc. are not as computer literate as they would like to be! So that simplicity & ease of use is important criteria for a plugin's ultimate acceptance.

Ciao, Yoel

**Comment by SimonMayerhofer** [comment]
HI Yoel,
thanks for clarifying. As this always depends on the theme and how the site is structured it's not something I think should be part of this plugin.
Maybe you can search for some plugin which displays posts for specific post types with a shortcode which you can then include in your pillar pages.
If you look for a way to include it in your theme, you can search for "custom post type query" and find a lot of resources.
The post type name is always `pillar-page-{ID}`, where ID is the ID of the page you entered in the settings. So e.g. `pillar-page-6592`.
Please be aware: this plugin does not create archive pages as the "archive" is the pillar page.
If you need further informations, let me know.
