### ISSUE TITLE
Missing Comments Flag in Pillar Pages

### ISSUE THREAD

**Issue by learningleanil** [SimonMayerhofer/wp-post-pillar-pages#2]
You hopefully remember that I am one of the Pillar Page Wordpress plugin's greatest fans!  I'm in the middle of creating a new Inbound Marketing Optimized website that uses the plugin (maybe too much :-) and I just discovered - all the Custom Post Types created with the Pillar Page Plugin lack the code to display Comments.  Allow Pingbacks & Trackbacks are included but not the "Discussion Flag"

I tried to figure out how to modify your code so that it adds "Discussion"

e.g.
/* If comments are open or we have at least one comment, load up the comment template */
						if ( comments_open() || '0' != get_comments_number() ) {
							comments_template();
						}

Any suggestions? In which of your files should I attempt to modify the code to include this insertion of the Comment Template?

**Comment by learningleanil** [comment]
Thanks in advance for any & all assistance extended!  Yoel

**Comment by SimonMayerhofer** [comment]
Hi Yoel,
can you please try to [extend the array at pillar-pages.php#L112](https://github.com/SimonMayerhofer/wp-post-pillar-pages/blob/dc77dc049a83879835d16b7c95873b9192d85054/pillar-pages.php#L112) with `comments`?
So that it looks like:
```php
'supports'     => [
	'title',
	'editor',
	'author',
	'thumbnail',
	'excerpt',
	'trackbacks',
	'custom-fields',
	'revisions',
	'post-formats',
	'comments',
],
```

**Comment by learningleanil** [comment]
Many thanks. I suggest you update the Github version. This is a very common
requirement. NOW I can write a glowing review and let the world know how to
create Hubspot Pillar Pages in Wordpress!

Ciao, Yoel


[image: photo]
Lean Startup Evangelist, Learning Lean (IL)
A  POB 9056 Shilo 4483000 Israel
O  +972 (2) 994-4532  <+972 (2) 994-4532> M  +972 (50) 255-5748  <+972 (50)
255-5748> E  info@LearningLean.Training  <info@LearningLean.Training>
W  https://www.LearningLean.Training
<http://medium.com/LearningLeanIL> <http://www.facebook.com/LearningLeanIL>
<http://linkedin.com/company/learningleanil>
<http://www.twitter.com/learningleanil>

If you received this email in error, please notify us immediately by
sending an e-mail or by calling.

**Comment by SimonMayerhofer** [comment]
Thanks for testing. Added in the newest version.
