### ISSUE TITLE
Trying to access array offset on value of type bool 

### ISSUE THREAD

**Issue by qualmelhorproduto** [SimonMayerhofer/wp-post-pillar-pages#3]
Congrats on the plugin!

I have on 2 sites installed. The 3 use the Astra theme with Elementor.

I tried to install on a third party and it's giving this error:

Warning: Trying to access array offset on value of type bool in /home/domain/www/wp-content/plugins/wp-post-pillar-pages-develop/pillar-pages.php on line 79
class="home page-template-default page page-id-576 wp-custom-logo ast-desktop ast-page-builder-template ast-no-sidebar astra-4.1.5 group-blog ast-single-post ast-inherit-site-logo-transparent ast-hfb-header ast-full-width-primary-header elementor-default elementor-kit-324 elementor-page elementor-page-576">
Warning: Trying to access array offset on value of type bool in /home/domain/www/wp-content/plugins/wp-post-pillar-pages-develop/pillar-pages.php on line 79

**Comment by SimonMayerhofer** [comment]
Can you please test if this is fixing your issue?

Edit pillar-pages.php and replace line 78 to 92 with this:

```
private function get_pillar_pages() {
    $pillar_pages_option = get_option('pillar_pages');

    if (!$pillar_pages_option || !isset($pillar_pages_option['post_ids'])) {
        return []; // Return an empty array or handle the error in an appropriate way.
    }

    $post_ids = explode(',', $pillar_pages_option['post_ids']);
    $pillar_pages = [];

    foreach ($post_ids as $id) {
        // skip if post with id does not exist.
        if (false === get_post_status($id)) {
            continue;
        }

        $pillar_pages[] = get_post($id);
    }

    return $pillar_pages;
}
```

**Comment by qualmelhorproduto** [comment]
Worked perfectly

Changed 10 posts to pillar.

Thank you very much!

[image: pillar-alteration.JPG][image: pillar-alteration2.JPG]

Em seg., 21 de ago. de 2023 às 06:23, Simon Mayerhofer <
***@***.***> escreveu:

**Comment by qualmelhorproduto** [comment]
Worked perfectly

Changed 10 posts to pillar.

Thank you very much!
